import React, { useContext } from "react";
import "./../globals.css";
import Footer from "@/shared/Footer";
import { AuthContextProvider } from "../provider/context/AuthContext";
import MyNavbar from "@/shared/MyNavbar";
import { Toaster } from 'react-hot-toast';


export const metadata = {
  title: 'BookFlow',
  description: 'Generated by create next app',
};

const Layout = ({ children }) => {
  return (
    <div className={``}>
      <AuthContextProvider>
        <MyNavbar />
        {children}
        <Toaster position="top-right" />
        <Footer />
      </AuthContextProvider>
    </div>
  );
};

export default Layout;
