import { Merriweather } from 'next/font/google'
import * as React from "react";
import './globals.css';
<<<<<<< HEAD
import Footer from '@/shared/Footer';
import { AuthContextProvider } from './context/AuthContext';
import Navbar from '@/shared/Navbar';
import NextThemeProvider from './provider/provider';

const inter = Inter({ subsets: ['latin'] });
=======
import Navbar from '@/shared/Navbar';
import Footer from '@/shared/Footer';


const merriweather = Merriweather({
   subsets: ['latin'],
   weight: ['400', '300', '700', '900']
  });

>>>>>>> ea3840f9d526b0ef6032ce41ec14528a00519bd2
export const metadata = {
  title: 'BookFlow',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning={true}>
<<<<<<< HEAD
      <body className={inter.className}>
        <AuthContextProvider>
          <Navbar />
          <NextThemeProvider>
            {children}
          </NextThemeProvider>
          <Footer />
        </AuthContextProvider>
=======
      <Head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content={metadata.description} />
        <link rel="shortcut icon" href={favicon} />
        <title>{metadata.title}</title>
      </Head>
      <body className={merriweather.className}>
        <Navbar />
        {children}
        <Footer />
>>>>>>> ea3840f9d526b0ef6032ce41ec14528a00519bd2
      </body>
    </html >
  );
};

export default RootLayout;
