import { Inter } from 'next/font/google'
import * as React from "react";
import './globals.css';
import Footer from '@/shared/Footer';
import Navbar from '@/shared/Navbar';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'BookFlow',
  description: 'Generated by create next app',
};
const RootLayout = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html >
  );
};

export default RootLayout;
